pipeline {
    agent any 
    environment {
        AWSRegistry = '314525640319.dkr.ecr.us-west-1.amazonaws.com/gal-repo'
        AWScredentialsId = '20aa853b-0b70-47e4-97fa-122fc4e0df60'
        GitURL = 'https://github.com/galfrylich/devops-task'
        GitcredentialsId = 'be180531-f264-44fe-897e-818a60362759'
    }
    stages {
        stage('Git Checkout') {
            steps {
                echo '# # # # # STAGE 1 - Git checkout # # # # #'
                checkout([$class: 'GitSCM',
                 branches: [[name: '*/main']], 
                 extensions: [], 
                 userRemoteConfigs: [[credentialsId: "$GitcredentialsId",
                 url: "$GitURL"]]])
                 sh 'git branch -a'
                 sh 'ls -al'

            }
        }
        stage('Build docker image') {
            steps {
                echo '# # # # # STAGE 2 - Build Image # # # # #'
                script{
                    dockerImage = docker.build("$AWSRegistry:latest", "-f hello-world/Dockerfile .")


                }
            }
        }
        stage('push image to erc') {
            steps {
                script{
                    echo '# # # # # STAGE 3 - Push Image # # # # #'
                    withAWS(credentials: 'aws', region: 'us-west-1'){
                        sh 'echo hello'
                        sh 'docker push $AWSRegistry:latest'
                    }
                    
                    }
                }
            }
        }
        
  
}