pipeline {
    agent any 
    environment {
        AWSRegistry = '314525640319.dkr.ecr.us-west-1.amazonaws.com/gal-repo'
        AWScredentialsId = '8460b74d-d6e5-447a-9386-dbd0d8a415e6'
        GitURL = 'https://github.com/galfrylich/devops-task'
        GitcredentialsId = 'be180531-f264-44fe-897e-818a60362759'
    }
    stages {
        stage('Git Checkout') {
            steps {
                echo '# # # # # STAGE 1 - Git checkout # # # # #'
                checkout([$class: 'GitSCM',
                 branches: [[name: '*/main']], 
                 extensions: [], 
                 userRemoteConfigs: [[credentialsId: "$GitcredentialsId",
                 url: "$GitURL"]]])
                 sh 'git branch -a'
                 sh 'ls -al'

            }
        }
        stage('Build docker image') {
            steps {
                echo '# # # # # STAGE 2 - Build Image # # # # #'
                script{
                    dockerImage = docker.build("$AWSRegistry:${BUILD_NUMBER}", "-f hello-world/Dockerfile .")


                }
            }
        }
        stage('push image to erc') {
            steps {
                    withAWS(credentials: "$AWScredentialsId"){
                        sh 'aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 314525640319.dkr.ecr.us-west-1.amazonaws.com'
                        sh 'echo hello'
                        sh 'docker push $AWSRegistry:${BUILD_NUMBER}'
                    }
                }
            }
        stage('deploy to cluster') {
        steps {
                sh ""
                helm upgrade --install hello-world ./hello-world-app --set image.tag=${BUILD_NUMBER}
            }
        }
        }
        
  
}